all:
	# arm-linux-gcc -o ./bin/cqupt ./src/*.c -I ./include/ -std=c99
	# arm-linux-gcc -o ./bin/loop1 ./src/*.c -I ./include/ -std=c99
	# arm-linux-gcc -o ./bin/loop ./src/*.c -I ./include/ -std=c99
	 arm-linux-gcc -o ./bin/loop_3color ./src/*.c -I ./include/ -std=c99